name: CI

on:
  push:
    branches: [ "main", "*" ]
  pull_request:
    branches: [ "main", "*" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test:
    name: Build & Test (Android Emulator + Appium)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: default
          profile: pixel_5
          script: |
            npm ci
            npx appium driver install uiautomator2
            npx appium --log-level error & npx wait-on tcp:4723
            npm run test
            npm run allure:generate

      - name: Upload allure-results (artefato)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload allure-report (artefato)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Allure to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
