name: CI

on:
  push:
    branches: ["*"]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Build & Test (Android Emulator + Appium)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            set -euo pipefail
            node -v
            java -version

            # Dependências do projeto
            npm ci

            echo "==> Instalando Appium 3 (next) globalmente"
            npm i -g appium@next

            echo "==> Descobrindo binário global do npm"
            APP_BIN="Unknown command: "bin"  To see a list of supported npm commands, run:   npm help"
            echo "npm bin -g: "
            "/appium" -v || true

            echo "==> Instalando driver uiautomator2 com Appium 3 global"
            if ! "/appium" driver install uiautomator2; then
              echo "Fallback: usando npx appium@next"
              npx --yes appium@next driver install uiautomator2
            fi

            echo "==> Listando drivers instalados (Appium 3)"
            "/appium" driver list --installed || npx --yes appium@next driver list --installed

            echo "==> Executando testes"
            npm run test:android:ci

            echo "==> Gerando relatório Allure"
            npm run allure:generate

      - name: Save Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Save Allure site
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-site
          path: allure-report

  deploy-pages:
    name: Deploy Allure to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download allure-site artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-site
          path: ./allure-site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
