name: Android E2E (WDIO + Appium) & Allure

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  test-android:
    name: Build & Test (Android Emulator + Appium)
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install deps
        run: |
          set -euxo pipefail
          npm ci
          # Garantir Appium + driver sempre atualizados (local via npx)
          npx -y appium@latest --version
          npx -y appium@latest driver install uiautomator2@latest || npx -y appium@latest driver update uiautomator2 || true
          npx -y appium@latest driver list --installed || true

      - name: Download APK (robusto, sem --latest)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          tmpdir=$(mktemp -d)
          TAG=$(gh release list --repo webdriverio/native-demo-app --limit 1 | awk 'NR==1{print $1}')
          if [ -z "$TAG" ]; then TAG="v1.0.8"; fi
          gh release download "$TAG" --repo webdriverio/native-demo-app -D "$tmpdir" -p '*[Aa]ndroid*apk'
          APK_FILE=$(find "$tmpdir" -name '*.apk' | head -n1)
          mv "$APK_FILE" app.apk
          # Checagem rápida do header (PK)
          [ "$(head -c2 app.apk | hexdump -v -e '/1 "%02X"')" = "504B" ]
          echo "APK_PATH=$GITHUB_WORKSPACE/app.apk" >> "$GITHUB_ENV"

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel 5
          force-avd-creation: true
          emulator-boot-timeout: 1200
          disable-animations: true
          emulator-options: -no-window -no-snapshot -no-boot-anim -gpu swiftshader_indirect -camera-back none -camera-front none -no-metrics
          script: |
            set -euxo pipefail

            adb devices
            adb wait-for-device
            adb shell getprop ro.build.version.release || true

            # Inicia Appium (local, sempre @latest)
            npx -y appium@latest --base-path / --log-level warn > ci-logs/appium.log 2>&1 &
            for i in {1..180}; do (nc -z 127.0.0.1 4723 && break) || sleep 1; done

            # Cria um override do WDIO p/ rodar CI sem mexer no seu arquivo
            cat > wdio.ci.android.conf.js <<'EOF'
            const { config } = require('./wdio.android.local.conf.js');
            // Garantir 1 sessão por vez
            config.maxInstances = 1;
            const caps = Array.isArray(config.capabilities) ? config.capabilities : [config.capabilities || {}];
            config.capabilities = caps.map(c => ({
              ...c,
              maxInstances: 1,
              // Evita erros "hidden_api_policy_*"
              'appium:ignoreHiddenApiPolicyError': true,
              // Evita instalar/abrir io.appium.settings
              'appium:skipDeviceInitialization': true,
            }));
            module.exports.config = config;
            EOF

            # (Opcional) sanity check do override
            node -e "const c=require('./wdio.ci.android.conf.js').config; if(c.maxInstances!==1) process.exit(1); console.log('WDIO CI override OK')"

            # Roda 100% sequencial: um spec por vez (evita colisão no emulador)
            EXIT=0
            for SPEC in $(ls -1 test/specs/*.spec.js); do
              echo ">>> Running spec: $SPEC"
              npx wdio run wdio.ci.android.conf.js --spec "$SPEC" || EXIT=$?
              if [ $EXIT -ne 0 ]; then break; fi
            done
            exit $EXIT

      - name: Upload CI logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: ci-logs/*

      - name: Gerar Allure site
        if: always()
        run: |
          set -euxo pipefail
          npx allure generate --clean allure-results -o allure-site || true

      - name: Upload Allure site (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-site
          path: allure-site

  deploy-allure:
    name: Deploy Allure to GitHub Pages
    needs: test-android
    if: always()
    runs-on: ubuntu-latest
    concurrency:
      group: gh-pages
      cancel-in-progress: true
    steps:
      - name: Download Allure site
        uses: actions/download-artifact@v4
        with:
          name: allure-site
          path: ./allure-site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
